// Generated by CoffeeScript 1.7.1
(function() {
  var loadUsers;

  loadUsers = function() {
    return $.get('/admin/viewUsers', function(data, txtStatus, jqXHR) {
      var user, _i, _len, _results;
      $('#userdata').empty();
      _results = [];
      for (_i = 0, _len = data.length; _i < _len; _i++) {
        user = data[_i];
        _results.push($('#userdata').append('<tr><td>' + user.uid + '</td><td>' + user.email + '</td><td class="ui left pointing dropdown">' + user.status + '<div class="menu"><div class="item">asdf</div></div></td></tr>'));
      }
      return _results;
    });
  };

  $(Document).ready(function() {
    $('.ui.table').hide();
    loadUsers();
    return $('#userstuff').show();
  });

  $('.ui.dropdown').dropdown();

  $('#users').click(function() {
    $('.ui.table').hide();
    loadUsers();
    return $('#userstuff').show();
  });

  $('#experis').click(function() {
    $('.ui.table').hide();
    return $('#experistuff').show();
  });

}).call(this);

//# sourceMappingURL=admin-gui.map
