// Generated by CoffeeScript 1.7.1
(function() {
  var nodemailer, sendEmail, settings, smtpTransport;

  nodemailer = require('nodemailer');

  settings = require('../config');

  smtpTransport = nodemailer.createTransport("SMTP", settings.confMail.smtp);

  sendEmail = function(target, subj, content, callback) {
    var mailOptions;
    mailOptions = {
      from: settings.confMail.content.from,
      to: target,
      subject: subj,
      html: content,
      generateTextFromHtml: true
    };
    return smtpTransport.sendMail(mailOptions, callback);
  };

  exports.sendEmail = sendEmail;

}).call(this);

//# sourceMappingURL=emailer.map
